version: '3.1'

services:
  mongo:
    image: mongo
    volumes:
      - /e/Container-Docker/Databases/db/Mongo
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234